version: 2.1

jobs:
  hello-job:
    docker:
#      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
      - image: circleci/openjdk:8-buster-node-browsers-legacy
#        auth:
#          username: mydockerhub-user
#          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
#      - run: echo "hello world" # run the `echo` command
      - run: ./gradlew stage
      - store_artifacts:
         path: ./lib/build/libs/all-in-one-jar.jar

workflows:
  my-workflow:
    jobs:
      - hello-job
